# This file was generated by GoReleaser. DO NOT EDIT.
cask "granola-obsidian-sync" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5ae028fc9eb4079a032f65f85944f47909994f2cd0fa268246b407514fd0f696"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b030188a97610bff5b761d58882b877918238bd0cd3992d018a15c148969526"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9bd59a43e0283466848b1772d717e83be96a2386344439204ea8c9a1a4c6f5a3"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "622a626fb3fd87ff3ba00490fc37db6bc54cdbf616935abdc8d1549f6402af5e"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "granola-obsidian-sync"
  desc "Incrementally mirror Granola transcripts into Obsidian"
  homepage "https://github.com/2389-research/granola-obsidian-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "granola-obsidian-sync"

  # No zap stanza required
end
