# This file was generated by GoReleaser. DO NOT EDIT.
cask "granola-obsidian-sync" do
  version "0.0.0-verification.1"

  on_macos do
    on_intel do
      sha256 "3ba6abd8fade9dd0dba8fe351c05e77b8d861900ac2936e61ba06c674c40f176"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "98cee5636d9f41914033abe1d2d777d87e03e8fc120771b56bd0df0aa59309d8"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "458e22b0d3321469884f550e35c73dddc6f28f8990ca2fec8e52ea8f08516c9e"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "81efb2c8c6db18d5baad5bf7f5335c371a582f7a2bd72cc68b04f94b68f69295"
      url "https://github.com/2389-research/granola-obsidian-sync/releases/download/v#{version}/granola-obsidian-sync_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "granola-obsidian-sync"
  desc "Incrementally mirror Granola transcripts into Obsidian"
  homepage "https://github.com/2389-research/granola-obsidian-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "granola-obsidian-sync"

  # No zap stanza required

end
