# This file was generated by GoReleaser. DO NOT EDIT.
cask "plaza" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "ac18221ecf12f59e14c089074892c116a69da9a10dc48fb8993bd303bb291be7"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "445fcd7573d35572c73c1933a490c459292249ed241ebc513a7ad544866040a7"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "678ff0e7edf7880c3efae8683f721492066354ed7bf0032b1cac498464ecab5e"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "af5c95994f778043dfac656b2d60c39249f92c88ae6674c496bd71df594b584d"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-arm64.tar.gz"
    end
  end

  name "plaza"
  desc "CLI for Plaza, the shared workspace for humans and agents"
  homepage "https://plaza.2389.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plaza"

  # No zap stanza required

end
