# This file was generated by GoReleaser. DO NOT EDIT.
cask "plaza" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6c73af0b8b3ad0a2956b003a0374c0d67f7faaf61b9dff97e83b1eacfecd808b"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "b5b026db90c36b32bdaf1abe33ac8889fb56a27e1ca3a69366799b14fdfb815d"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "437cae563d8b596d34c12b220c183f5d6df4c9201e3f52df9ae58dc5ea44ddaa"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "49328a6e5fae03885a729b0bc5f5b76ad22e198b4ab7b18bedfbc5e0954129d7"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-arm64.tar.gz"
    end
  end

  name "plaza"
  desc "CLI for Plaza, the shared workspace for humans and agents"
  homepage "https://plaza.2389.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plaza"

  # No zap stanza required

end
