# This file was generated by GoReleaser. DO NOT EDIT.
cask "plaza" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ba10cad73f36aca10dbeb361abe4b4be8e7ba7bfe0185a560fcd9449d3932d8c"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "de42b173d657be1c85e6aec74cb8aecd4659e935c626a17a3779f514dbc26079"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7cdba823ec3c4852aea9e2d61bcb601ba1753155db02276cbb00ab1a64bb7ce"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "153d76ead6772bf6f782129c8dfb9e7a85e758c54412b949b045bbe6d2259383"
      url "https://plaza.2389.ai/cli/v#{version}/plaza-linux-arm64.tar.gz"
    end
  end

  name "plaza"
  desc "CLI for Plaza, the shared workspace for humans and agents"
  homepage "https://plaza.2389.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plaza"

  # No zap stanza required

end
