# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccut < Formula
  desc "Claude Code usage tracker - monitor your API usage from the terminal"
  homepage "https://github.com/2389-research/ccut"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/ccut/releases/download/v0.1.1/ccut_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "af44e3ab0f0987d07cbf8e49d83cda9803c21ae93b4592f15ee7eb1b40736d56"

      define_method(:install) do
        bin.install "ccut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/ccut/releases/download/v0.1.1/ccut_0.1.1_Darwin_arm64.tar.gz"
      sha256 "298097ee3e554373867f34c778111f6cfbaeae8230ff9148c72507181042fcf6"

      define_method(:install) do
        bin.install "ccut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/ccut/releases/download/v0.1.1/ccut_0.1.1_Linux_x86_64.tar.gz"
      sha256 "69a04c0ca873e7b7e7529dbe19afc4ef63e29540597fab41792748d44e190ec8"
      define_method(:install) do
        bin.install "ccut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/ccut/releases/download/v0.1.1/ccut_0.1.1_Linux_arm64.tar.gz"
      sha256 "e32ca2b935e974b60e58f5408d3246451393c6557f22593b7325df42bcdd8a63"
      define_method(:install) do
        bin.install "ccut"
      end
    end
  end

  test do
    system "#{bin}/ccut", "--help"
  end
end
