# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccvault < Formula
  desc "Claude Code conversation archive and analysis tool"
  homepage "https://github.com/2389-research/ccvault"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/ccvault/releases/download/v0.1.2/ccvault_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "bfea72d1b46977b3d3db41933b33c45f95063207055af88313b05979cd6e4ad7"

    def install
      bin.install "ccvault"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/ccvault/releases/download/v0.1.2/ccvault_0.1.2_Darwin_arm64.tar.gz"
    sha256 "2de5108f68c24edc62410253d9a94ad2b5fbfd0030dc273e5104229268c63f43"

    def install
      bin.install "ccvault"
    end
  end

  test do
    system "#{bin}/ccvault", "version"
  end
end
