# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccvault < Formula
  desc "Claude Code conversation archive and analysis tool"
  homepage "https://github.com/2389-research/ccvault"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/ccvault/releases/download/v0.1.1/ccvault_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "68ac144905bc049027350ccf5b53660653cab3539715b8eb61b4980549cbecc9"

    def install
      bin.install "ccvault"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/ccvault/releases/download/v0.1.1/ccvault_0.1.1_Darwin_arm64.tar.gz"
    sha256 "1c586b3e1d0373df0a2dfbd3a8451b10c0e41655c66057c77d969298fd9ce5af"

    def install
      bin.install "ccvault"
    end
  end

  test do
    system "#{bin}/ccvault", "version"
  end
end
