# ABOUTME: Installs coven-gateway release binaries for macOS and Linux through Homebrew.
# ABOUTME: Selects platform-specific v0.6.1 archives and verifies their published checksums.
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CovenGateway < Formula
  desc "Gateway server for AI agent orchestration"
  homepage "https://github.com/2389-research/coven-gateway"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/coven-gateway/releases/download/v0.6.1/coven-gateway_0.6.1_darwin_amd64.tar.gz"
      sha256 "ca477995361ea80f52b6f77030cd8b8655356a4b9959d3dafd811b5a15c791ff"

      define_method(:install) do
        bin.install "coven-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/coven-gateway/releases/download/v0.6.1/coven-gateway_0.6.1_darwin_arm64.tar.gz"
      sha256 "28a7cc85d634ad6cc4c1ddc2ca400394c9bf90fef96dcd9dfa78d20f3f1f2f1a"

      define_method(:install) do
        bin.install "coven-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/coven-gateway/releases/download/v0.6.1/coven-gateway_0.6.1_linux_amd64.tar.gz"
      sha256 "60a6221cd1e8d39e0fa52db05bd9cc559893126162f1c74b11e73e00f8789fcc"
      define_method(:install) do
        bin.install "coven-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/coven-gateway/releases/download/v0.6.1/coven-gateway_0.6.1_linux_arm64.tar.gz"
      sha256 "0b51393d827dd784f3bd04a475fcf29d6b8ae38a27cf89f445d286994aa131a6"
      define_method(:install) do
        bin.install "coven-gateway"
      end
    end
  end

  test do
    assert_match "Usage: coven-gateway <command>", shell_output("#{bin}/coven-gateway 2>&1", 1)
  end
end
