# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DippinLang < Formula
  desc "A pipeline-aware workflow definition language"
  homepage "https://github.com/2389-research/dippin-lang"
  version "0.68.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.68.0/dippin-lang_0.68.0_Darwin_x86_64.tar.gz"
      sha256 "ddf809df4a76c87102089fcef219ac371ecbba3b1a3f8c95f5d2e2a27c499325"

      define_method(:install) do
        bin.install "dippin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.68.0/dippin-lang_0.68.0_Darwin_arm64.tar.gz"
      sha256 "923a2d569017ea8061f66a4eca120476500e04941aea026716ce266122dee43d"

      define_method(:install) do
        bin.install "dippin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.68.0/dippin-lang_0.68.0_Linux_x86_64.tar.gz"
      sha256 "8e7544934bff846459c8435c3cdd3bb45fa76aa642c2d45ffc342391de2d451f"
      define_method(:install) do
        bin.install "dippin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.68.0/dippin-lang_0.68.0_Linux_arm64.tar.gz"
      sha256 "dcdb2114b9e114226f9746edef070f721082d31bf31e36b091cfd781903297d9"
      define_method(:install) do
        bin.install "dippin"
      end
    end
  end

  test do
    system "#{bin}/dippin", "version"
  end
end
