# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DippinLang < Formula
  desc "A pipeline-aware workflow definition language"
  homepage "https://github.com/2389-research/dippin-lang"
  version "0.25.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.25.0/dippin-lang_0.25.0_Darwin_x86_64.tar.gz"
      sha256 "2e176e69647a50a86d0c395c0031e6eab4fe8494bd07fc000c40304dfddb51fe"

      define_method(:install) do
        bin.install "dippin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.25.0/dippin-lang_0.25.0_Darwin_arm64.tar.gz"
      sha256 "95d073bfa1dde99179619b95439bb57d2da74a9651b545a5302098aa917522fb"

      define_method(:install) do
        bin.install "dippin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.25.0/dippin-lang_0.25.0_Linux_x86_64.tar.gz"
      sha256 "7d20acacafb5407e7bfa07589c5e2ef4a423eabd7035a5641abefb7b4e83b823"
      define_method(:install) do
        bin.install "dippin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/dippin-lang/releases/download/v0.25.0/dippin-lang_0.25.0_Linux_arm64.tar.gz"
      sha256 "93697065b97cbffc8b7227f86189cc103c9acb96c5e5265dcfe0d47edd8724af"
      define_method(:install) do
        bin.install "dippin"
      end
    end
  end

  test do
    system "#{bin}/dippin", "version"
  end
end
