# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossip < Formula
  desc "Labeled, decaying, evidence-badged hearsay in a shared SQLite file"
  homepage "https://github.com/2389-research/gossip"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/gossip/releases/download/v0.1.0/gossip_0.1.0_darwin_amd64.tar.gz"
      sha256 "a0cc878b8083396d60e38f72a212f02bc53ab42643b54a631a16c1b84c777eff"

      define_method(:install) do
        bin.install "gossip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/gossip/releases/download/v0.1.0/gossip_0.1.0_darwin_arm64.tar.gz"
      sha256 "6c981844035ee35fd7aa2b95392aa7b13dd1536de34cf20482a73c663566a6a8"

      define_method(:install) do
        bin.install "gossip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/gossip/releases/download/v0.1.0/gossip_0.1.0_linux_amd64.tar.gz"
      sha256 "996f07854d49aaad1467d2afe7f1546c2e49a81d2acd83edf95ca5d866f9559c"
      define_method(:install) do
        bin.install "gossip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/gossip/releases/download/v0.1.0/gossip_0.1.0_linux_arm64.tar.gz"
      sha256 "afc87d01056a7547df0880668bc37d38f4707159a25ce5bc18650c07543eae65"
      define_method(:install) do
        bin.install "gossip"
      end
    end
  end

  test do
    system "#{bin}/gossip", "--version"
  end
end
