# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GsuiteMcp < Formula
  desc "GSuite MCP Server - Model Context Protocol server for Google Workspace APIs"
  homepage "https://github.com/2389-research/gsuite-mcp"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/gsuite-mcp/releases/download/v1.0.5/gsuite-mcp_1.0.5_darwin_amd64.tar.gz"
      sha256 "4930f45c34fc025538d653275dcd61a246ab23b38b0f64fefeda3b858ef45e8b"

      def install
        bin.install "gsuite-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/gsuite-mcp/releases/download/v1.0.5/gsuite-mcp_1.0.5_darwin_arm64.tar.gz"
      sha256 "9c0b12d2039e29e5d43ec6d934ba36a864386800d8b885bfe9b8e2a531cb47b3"

      def install
        bin.install "gsuite-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/gsuite-mcp/releases/download/v1.0.5/gsuite-mcp_1.0.5_linux_amd64.tar.gz"
      sha256 "0adb3ce296316d0b20b49c4020efef765a181ffe92a95c1871edf88a645b298c"
      def install
        bin.install "gsuite-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/gsuite-mcp/releases/download/v1.0.5/gsuite-mcp_1.0.5_linux_arm64.tar.gz"
      sha256 "74e08c6660cb880dc9180ee3c9fecca48053559651b34451016332bf00fc1cf7"
      def install
        bin.install "gsuite-mcp"
      end
    end
  end

  test do
    system "#{bin}/gsuite-mcp", "--help"
  end
end
