# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hex < Formula
  desc "Powerful CLI for Claude AI, inspired by Claude Code, Crush, Codex, and MaKeR"
  homepage "https://github.com/2389-research/hex"
  version "1.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/hex/releases/download/v1.8.0/hex_1.8.0_Darwin_x86_64.tar.gz"
      sha256 "1bb0f31add4f60a664c11380728ebf4b6331f6e959f585248b9fa1ed8ddf07b5"

      def install
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/hex/releases/download/v1.8.0/hex_1.8.0_Darwin_arm64.tar.gz"
      sha256 "acd6e301f9ab78200b62e946e2bbd7dd7ddb28731b8bfdfcfd0e806a710bbac2"

      def install
        bin.install "hex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.8.0/hex_1.8.0_Linux_x86_64.tar.gz"
      sha256 "789ff7f68ad3c75e0484896e23c7c2ba216e1107c7f4b9dbf44105f0b725ebce"
      def install
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.8.0/hex_1.8.0_Linux_arm64.tar.gz"
      sha256 "9e0e0806c9ad9bf41bf48871b683cd010621672c0e9f7c04e2665796082e22c2"
      def install
        bin.install "hex"
      end
    end
  end

  test do
    system "#{bin}/hex", "--version"
  end
end
