# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hex < Formula
  desc "Powerful CLI for Claude AI, inspired by Claude Code, Crush, Codex, and MaKeR"
  homepage "https://github.com/2389-research/hex"
  version "1.11.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/hex/releases/download/v1.11.3/hex_1.11.3_Darwin_x86_64.tar.gz"
      sha256 "4461b58694468919e20b9446ff1771aa70d408ce5dcb360f7b1ac5f308004f9c"

      define_method(:install) do
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/hex/releases/download/v1.11.3/hex_1.11.3_Darwin_arm64.tar.gz"
      sha256 "9d710b5f3648dc942f37877040f5fab2a2e34d33700e14819b49408ecfbed37e"

      define_method(:install) do
        bin.install "hex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.11.3/hex_1.11.3_Linux_x86_64.tar.gz"
      sha256 "4912a2cc0eb03d96a169ecf604f9b0badc3bef9055a058e9a4ec7c3633d71362"
      define_method(:install) do
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.11.3/hex_1.11.3_Linux_arm64.tar.gz"
      sha256 "eb7f435e71a93d226c2553f3f9cbac0309f9e1f60f064f8bb0b5f5ed974a3a69"
      define_method(:install) do
        bin.install "hex"
      end
    end
  end

  test do
    system "#{bin}/hex", "--version"
  end
end
