# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hex < Formula
  desc "Powerful CLI for Claude AI, inspired by Claude Code, Crush, Codex, and MaKeR"
  homepage "https://github.com/2389-research/hex"
  version "1.12.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/hex/releases/download/v1.12.1/hex_1.12.1_Darwin_x86_64.tar.gz"
      sha256 "bc3943a6ac9e0193920822ab0945ae014febcfb9362d0115236abe2c198167f4"

      define_method(:install) do
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/hex/releases/download/v1.12.1/hex_1.12.1_Darwin_arm64.tar.gz"
      sha256 "bf45b073261e323c865cdc97c2651792c04578d9c86be7e3fc88bade2c00977a"

      define_method(:install) do
        bin.install "hex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.12.1/hex_1.12.1_Linux_x86_64.tar.gz"
      sha256 "59a04867c05a20f142ba23e18346e7f90477c41e37fd7a6cc07780a2e47af5fe"
      define_method(:install) do
        bin.install "hex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/hex/releases/download/v1.12.1/hex_1.12.1_Linux_arm64.tar.gz"
      sha256 "0afe813c135b90bb11e104669f424e3e3b7bc7c95b87d5eb81aaf2c71be4f93f"
      define_method(:install) do
        bin.install "hex"
      end
    end
  end

  test do
    system "#{bin}/hex", "--version"
  end
end
