# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ish < Formula
  desc "ISH - Intelligent Server Hub for digital twin APIs"
  homepage "https://github.com/2389-research/ish"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/ish/releases/download/v0.5.2/ish_0.5.2_darwin_amd64.tar.gz"
      sha256 "c6bae8d440c382045046927034375e3fb926da5c3899992426567e561111510c"

      def install
        bin.install "ish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/ish/releases/download/v0.5.2/ish_0.5.2_darwin_arm64.tar.gz"
      sha256 "d9f93a3df38a520f8e9214b549ff2aac7047738377f821414b824ee39bdc23bd"

      def install
        bin.install "ish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/ish/releases/download/v0.5.2/ish_0.5.2_linux_amd64.tar.gz"
      sha256 "e56c8352b41d978647e04dddaebb6c7d578e923f26dc28085dccc7f096473e66"
      def install
        bin.install "ish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/ish/releases/download/v0.5.2/ish_0.5.2_linux_arm64.tar.gz"
      sha256 "4803df49841ad40d3db8ca99b2d727871862d1c4b3737dfd0751387548137950"
      def install
        bin.install "ish"
      end
    end
  end

  test do
    system "#{bin}/ish", "--help"
  end
end
