# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "Agent productivity suite — tasks, bugs, boards, DMs, docs, and more"
  homepage "https://github.com/2389-research/lotus"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/lotus/releases/download/v0.1.0/lotus_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "73c2f27a534d38178af3efdc9900e2e78a9e38cb1692be9428ef23f1ca6cfb15"

    define_method(:install) do
      bin.install "suite"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/lotus/releases/download/v0.1.0/lotus_0.1.0_Darwin_arm64.tar.gz"
    sha256 "5f9a8a81bf19616ab31c19178acf623609dc20e8899caa0dc3f7b6a2a6e38dd8"

    define_method(:install) do
      bin.install "suite"
    end
  end

  test do
    system "#{bin}/suite", "--help"
  end
end
