# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "Lotus — agent productivity suite for tasks, bugs, boards, DMs, docs, and more"
  homepage "https://github.com/2389-research/lotus"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/lotus/releases/download/v0.2.0/lotus_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "03ac658f3a30e3a990d652b04e8b9d2b607f4c1ca9f41aef32e31dcfa6bb81c5"

    define_method(:install) do
      bin.install "lotus"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/lotus/releases/download/v0.2.0/lotus_0.2.0_Darwin_arm64.tar.gz"
    sha256 "fbedec0f443e50c6f927a7df8474fceafd12ee03c63202c3bd29e21fbb56e820"

    define_method(:install) do
      bin.install "lotus"
    end
  end

  test do
    system "#{bin}/lotus", "--help"
  end
end
