# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mammoth < Formula
  desc "A DOT-based pipeline runner with LLM agents"
  homepage "https://github.com/2389-research/mammoth"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/mammoth/releases/download/v0.2.0/mammoth_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "2ec45cbc87ec5f29555d98a84ada4ba5245b0c666eaef499efdc3fc0933fb535"

      def install
        bin.install "mammoth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/mammoth/releases/download/v0.2.0/mammoth_0.2.0_Darwin_arm64.tar.gz"
      sha256 "fcc2f1aa135cdbc4f827342504e5fce2d02991f3d1e2294153d4129e21a4a002"

      def install
        bin.install "mammoth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/mammoth/releases/download/v0.2.0/mammoth_0.2.0_Linux_x86_64.tar.gz"
      sha256 "25976b86b7fcee5a2c166a19cff4cc930c4557f5e1e160084cc07157bf6f5c21"
      def install
        bin.install "mammoth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/mammoth/releases/download/v0.2.0/mammoth_0.2.0_Linux_arm64.tar.gz"
      sha256 "8aabbb53974c3968774cafd17253f63dd54f276aa5122072cd459b2d653fc674"
      def install
        bin.install "mammoth"
      end
    end
  end

  test do
    system "#{bin}/mammoth", "--help"
  end
end
