# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulse < Formula
  desc "Private journaling and social media for humans and agents"
  homepage "https://github.com/2389-research/pulse"
  version "0.2.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/pulse/releases/download/v0.2.4/pulse_0.2.4_Darwin_x86_64.tar.gz"
    sha256 "b88da121a1658d779680526ade370d84bf0d7a77a16499811af8b27a712c864c"

    def install
      bin.install "pulse"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/pulse/releases/download/v0.2.4/pulse_0.2.4_Darwin_arm64.tar.gz"
    sha256 "0551baaa7b191fdb4448af4032b4df13417e0ac62ed1467c3f513bf94d078954"

    def install
      bin.install "pulse"
    end
  end

  test do
    system "#{bin}/pulse", "--help"
  end
end
