# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulse < Formula
  desc "Private journaling and social media for humans and agents"
  homepage "https://github.com/2389-research/pulse"
  version "0.2.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2389-research/pulse/releases/download/v0.2.2/pulse_0.2.2_Darwin_x86_64.tar.gz"
    sha256 "9d0e8464b1acc585a8ad532d9aaa4a9e21d15fe97e3dece432b39982dcb6f788"

    def install
      bin.install "pulse"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2389-research/pulse/releases/download/v0.2.2/pulse_0.2.2_Darwin_arm64.tar.gz"
    sha256 "d3a6d3ce2250359fa7690653f6850d96450d129171593f366720959a329474a1"

    def install
      bin.install "pulse"
    end
  end

  test do
    system "#{bin}/pulse", "--help"
  end
end
