# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracker < Formula
  desc "Pipeline orchestration engine for multi-agent LLM workflows"
  homepage "https://github.com/2389-research/tracker"
  version "0.67.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/tracker/releases/download/v0.67.0/tracker_tracker_0.67.0_darwin_amd64.tar.gz"
      sha256 "1513cb2da0b3002875abb5e11d34bd2686d0de8f9d80d86ef6fa3817ccb6ec38"

      define_method(:install) do
        bin.install "tracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/tracker/releases/download/v0.67.0/tracker_tracker_0.67.0_darwin_arm64.tar.gz"
      sha256 "fd574b535dbd171d3abaa8ae0e536c1fed7669df84e1d58a294ece8b30a26f11"

      define_method(:install) do
        bin.install "tracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/tracker/releases/download/v0.67.0/tracker_tracker_0.67.0_linux_amd64.tar.gz"
      sha256 "4998a5ab33bd2a666632708780b9cb0e55ad7b419123e789755d393f49e947a4"
      define_method(:install) do
        bin.install "tracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/tracker/releases/download/v0.67.0/tracker_tracker_0.67.0_linux_arm64.tar.gz"
      sha256 "9741a8add6fcd78e90591d5de14c444239c9f5d9307758bfb7746b172bbc5584"
      define_method(:install) do
        bin.install "tracker"
      end
    end
  end

  test do
    # Assert the shipped binary reports its stamped identity, not a `dev`
    # build (SIFT-SUB-15-01 #593): the ldflags above must inject
    # main.version/commit/date into every published archive.
    output = shell_output("#{bin}/tracker version")
    assert_match "tracker #{version}", output
    refute_match "commit: unknown", output
    refute_match "built:  unknown", output
  end
end
