# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracker < Formula
  desc "Pipeline orchestration engine for multi-agent LLM workflows"
  homepage "https://github.com/2389-research/tracker"
  version "0.27.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/tracker/releases/download/v0.27.0/tracker_tracker_0.27.0_darwin_amd64.tar.gz"
      sha256 "34397eec7618ef56b19deb811b394ab796f946123fc7a512dfdb74cd08c03438"

      define_method(:install) do
        bin.install "tracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/tracker/releases/download/v0.27.0/tracker_tracker_0.27.0_darwin_arm64.tar.gz"
      sha256 "bfddd74346e645d52d69f58a0529ba613c999781f380d412ad36a2e44f171abe"

      define_method(:install) do
        bin.install "tracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/tracker/releases/download/v0.27.0/tracker_tracker_0.27.0_linux_amd64.tar.gz"
      sha256 "7c5ee59ccddba68b483f89706ddb2ac198e893fe012eb9973def5baef0f0045b"
      define_method(:install) do
        bin.install "tracker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/tracker/releases/download/v0.27.0/tracker_tracker_0.27.0_linux_arm64.tar.gz"
      sha256 "ba53540b518a28869f9a68b7a27ce41606c92f30d7ba9588a781bb17d940ab33"
      define_method(:install) do
        bin.install "tracker"
      end
    end
  end

  test do
    system "#{bin}/tracker", "version"
  end
end
