# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turtle < Formula
  desc "Duolingo-style terminal and tmux command trainer"
  homepage "https://github.com/2389-research/turtle"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "c135a963896d047fbc8499e3950a51e46d593e7983491c27b045d6392516c9aa"

      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Darwin_arm64.tar.gz"
      sha256 "58bb6e6d21663a6eac4d2b795cf0c99c9c31e402d2f2b5cba5b20046742856ab"

      def install
        bin.install "turtle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0334d44331b28892c940b024cd758df7c53f42a57f1c59eca7da60dcfbfdfb43"
      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Linux_arm64.tar.gz"
      sha256 "289015d7b2899f1414faee50a5ef061304c9576d9db82d6e30f53a6f926842e6"
      def install
        bin.install "turtle"
      end
    end
  end

  test do
    system "#{bin}/turtle", "--help"
  end
end
