# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turtle < Formula
  desc "Duolingo-style terminal and tmux command trainer"
  homepage "https://github.com/2389-research/turtle"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.2/turtle_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "4c472cb66c0dfdd67d7fedf1e27bae0e971745ad3d151330839d16ba9420d26c"

      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.2/turtle_0.1.2_Darwin_arm64.tar.gz"
      sha256 "5a4b29d6fd9234842cca815ba476428c21f34fedf6828bba604093c043fef611"

      def install
        bin.install "turtle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.2/turtle_0.1.2_Linux_x86_64.tar.gz"
      sha256 "a7c5ce5f717becc49f703491cf1f798f9a43e4c25063d0a9c025a578a9597442"
      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.2/turtle_0.1.2_Linux_arm64.tar.gz"
      sha256 "fa618bb1e6a10c7d80608851dbfe310700febb4c2f2824b2e7cfcd52865b37c1"
      def install
        bin.install "turtle"
      end
    end
  end

  test do
    system "#{bin}/turtle", "--help"
  end
end
