# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turtle < Formula
  desc "Duolingo-style terminal and tmux command trainer"
  homepage "https://github.com/2389-research/turtle"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "cc2792c015f0506781a1c2ac985216e42c070b67f8e72c118b8e1fc2729ca3b9"

      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Darwin_arm64.tar.gz"
      sha256 "e0d47c1b24a47a0d74f370036b74988477d9e7e1cccf6c5789bc1ec6ee74facc"

      def install
        bin.install "turtle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Linux_x86_64.tar.gz"
      sha256 "4ec55189887258d0f2aa425a5fc9a4abeea73c58ba67cb23b153a7feb3c0ca83"
      def install
        bin.install "turtle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2389-research/turtle/releases/download/v0.1.0/turtle_0.1.0_Linux_arm64.tar.gz"
      sha256 "0a62309603974377a427943559f7103708b3867df3b0cb6ed0e76547140a566e"
      def install
        bin.install "turtle"
      end
    end
  end

  test do
    system "#{bin}/turtle", "--help"
  end
end
